# Generated by Django 4.1.1 on 2022-10-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('city_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='department',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='address',
        ),
        migrations.RemoveField(
            model_name='department',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='department',
            name='salary',
        ),
    ]
